name: NPM Publish

on:
  workflow_run:
    workflows: ["Canary Release", "Stable release"]
    types: [completed]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Using VERSION=$VERSION"
          npm run build -- --define VERSION=$VERSION
          npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: btsd-aitu-bridge-*.tgz
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Package version: $VERSION"

          if [[ "$VERSION" == *"-canary."* ]]; then
            echo "Publishing canary version"
            npm publish --tag canary --access public
          else
            echo "Publishing latest version"
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
